### ISSUE TITLE
How to include non python configuration files

### ISSUE THREAD

**Issue by Pramodnair84** [pypa/sampleproject#183] opened 2023-01-03 15:40 UTC
I am trying to include ci configuration files which usually kept at project root etc directory at my org. The example here shows data files with in package. Adding path to MANIFEST.in did not work.

**Comment by jeanas** [comment] 2024-02-03 22:30
@Pramodnair84 Sorry that you didn't get an answer here. This was probably caused by an incorrect `MANIFEST.in` file. I'm going to close this issue as lacking information; if you still have this question, please ask for support on https://discuss.python.org/c/users/7. Thank you.

**Closed by jeanas** 2024-02-03 22:30 UTC
