### ISSUE TITLE
neither package_data or data_files get installed

### ISSUE THREAD

**Issue by ericfrederich** [pypa/sampleproject#30] opened 2015-05-01 15:02 UTC
I have tried this on Python 2.7.5 and Python 3.4.3 and am unable to see package_data.dat or data_file installed anywhere when I do "python setup.py install"
If I change to distutils it works fine.

**Comment by qwcode** [comment] 2015-05-01 20:36
can you provide details with a paste of your output

**Comment by qwcode** [comment] 2015-05-01 20:43
ok, I see.   it works when installing (using pip or easy_install) from a built sdist,  but not using "python setup.py install" from a checkout.   I wasn't aware.   will look into it.

**Comment by andyneff** [comment] 2015-05-21 23:52
I think this is related to @ericfrederich issue?

Test 1) If I do ```python setup.py install``` I get an egg containing both package_data.dat and data_file, similarly if I set zip_safe to False, I have those files both in the sample directory. 

Test 2) I create a wheel using ```pip wheel --wheel-dir=. sampleproject``` and when I do ```pip install sample-1.2.0-py2.py3-none-any.whl```the my_data\data_file works, and sample_data.dat

Test 3) But when I create a sdist (```python setup.py sdist```), the zip always contains package_data.dat (even if I comment out the package_data section), and never contains data_file.

    error: can't copy 'data\data_file': doesn't exist or not a regular file

Test 4) Now if I remove package_data.dat from MANIFEST.in, it only includes the package_data as I would have expected...I guess when creating an sdist, these files are ALWAYS added even after python 2.6 due to MANIFEST.in 

I guess this is all related to the same problem that's been plaguing sdist vs bdist forever http://blog.codekills.net/2011/07/15/lies,-more-lies-and-python-packaging-documentation-on--package_data-/ Although I don't know how much of that is still accurate or translates to setuptools, but I DO know the same problems appear to be happening...It's just this sample doesn't appear to work for both... YET?

Python 2.7.9 Windows 64-bit and Linux 64-Bit 
Setuptools 15.2 and 16.0 (And I even tried 1.0 for a few tests, nothing really changed)

**Comment by ionelmc** [comment] 2015-09-29 05:22
Neither `package_data` or `data_files` should be part of any "regular" project. They are ridiculously hard to get right. `data_files` behaves [inconsistently across tools](https://github.com/pypa/pip/issues/2874#issuecomment-109429489). I consider those anti-patterns in packaging [1]. Having a correct `MANIFEST.in` and `include_package_data=True` is most always the right choice.

[1] If you have the patience watch [this](https://ep2015.europython.eu/conference/talks/less-known-packaging-features-and-tricks)

**Comment by qwcode** [comment] 2015-10-13 01:16
yea @ionelmc , I think the sample project and the distribution tutorial needs some rehaul in this department.    just recommend the easiest thing (like in your video), and maybe have an advanced section to cover all the caveats etc... that are *so* hard to remember.

**Comment by lrq3000** [comment] 2016-10-03 01:51
Using `include_package_data=True` fixed the issue for me. Thank's @ionelmc !

**Comment by stuaxo** [comment] 2016-11-09 23:42
@ionelmc what is the way to include some data with a project, that will get installed into the virtualenv (and allow installation using pip) ?

**Comment by ionelmc** [comment] 2016-11-10 06:10
@stuaxo `MANIFEST.in` + `include_package_data=True` is my default approach. I'm not really sure what you're asking me, describe your situation more.

**Comment by stuaxo** [comment] 2016-11-10 10:20
Ah, was messing with this too late and had broken my MANIFEST.in.
Cheers for the pointer.

**Comment by laike9m** [comment] 2017-03-12 11:50
@ionelmc `MANIFEST.in` + `include_package_data=True` as best practice, So true! I spent hours debugging what's wrong with `package_data` and finally solved it by adding a MANIFEST.

**Comment by stuaxo** [comment] 2017-03-12 13:11
OT:  Setuptools is such a mess, and the defaults mean I have to look up how to do this every year or so.

I'm glad work is being done on it, but having delved inside, I think we'd be better off chucking it out and using something else at this point.

**Comment by fduxiao** [comment] 2018-08-24 05:26
When will this be fixed. You are justing wasting others' time, which is a kind of murder!

**Comment by stuaxo** [comment] 2018-08-24 10:49
@fduxiao it's funny, as I only package something about once a year, I always, without fail - forget how to add files to my python package, python packaging is almost always painful in some way.

**Comment by fduxiao** [comment] 2018-08-24 13:36
@stuaxo In my situation, I use cython to accelerate my web application, which requires non python templates and will be used further by other projects, and I found the only way that works is put an empty __init__.py into the templates dir and tell cython not to handle it (they are found automatically). It cost me more then 3 hours to find it. 
I think it will be great if there's a simple way to add non python files.

**Comment by nicktimko** [comment] 2018-08-27 23:06
@fduxiao is [the workaround](https://github.com/pypa/sampleproject/issues/30#issuecomment-143947944) of `MANIFEST.in` ([docs here](https://docs.python.org/3/distutils/commandref.html)) and `setup(..., include_package_data=True)` not working for you?

**Comment by fduxiao** [comment] 2018-09-01 14:27
@nicktimko See my fork [here](https://github.com/fduxiao/sampleproject). I'm not sure whether I write the `MANIFEST.in` correctly or not.

**Comment by nicktimko** [comment] 2018-09-02 18:14
Saying `graft data` would be slightly simpler than `recursive-include data *`, but does it not work now?

StackOverflow might be a better forum for such a question than here.

**Comment by fduxiao** [comment] 2018-09-03 07:39
@nicktimko It never works if my package has only compile modules (You see I just cythonized the modules and the data just fail to be installed). The conclusion I can get from stackoverflow is that it's only a [dirty lie](https://stackoverflow.com/questions/7522250/how-to-include-package-data-with-setuptools-distribute). I'm not asking a question. I'm saying one could not put package data for a package of compile modules. It may be caused by the fact that `setup` never thinks compiled modules as packages (they are under some folder) and I cannot specify the folder is actually a package, so can anyone find the reason and fix it?

**Comment by stuaxo** [comment] 2018-09-03 20:04
@fduxiao I had to do the thing with a fake ```__init__.py``` but it feels like a hack, the kind that might just stop working some day.

**Comment by ionelmc** [comment] 2018-10-04 12:07
@andreypanin `config.yml` is not inside the package named `sample` thus it doesn't qualify as package data, thus `include_package_data=True` won't have any effect. Move it inside the `sample` directory and use `graft sample` in the manifest (just that).

**Comment by KenTsui** [comment] 2019-07-24 03:14
Is this problem solved? I can use `package_data` to include my image files successfully into my package.

Python 3.7.3 64bit
setuptools - 40.8.0

**Comment by pradyunsg** [comment] 2019-07-24 05:20
I'm gonna go ahead and close this -- packagers should use `MANIFEST.in` and `include_package_data=True` to correctly choose which files get included.

You can look at the pip's setup.py and MANIFEST.in for a more concrete example.

If anyone has similar/other issues related to which files get included, please check if there's a related issue filed on setuptools' issue tracker, otherwise please file a new issue there. :)

Thanks everyone for chiming in here!

**Closed by pradyunsg** 2019-07-24 05:20 UTC

**Comment by pradyunsg** [comment] 2019-07-24 05:22
To be clear, using a different build tool like flit can help avoid these setuptools specific issues.

**Comment by lrq3000** [comment] 2020-03-12 00:22
With Python 3 I've found out that the MANIFEST.in is not honored anymore in the wheel, but it is in the tar.gz! Maybe this was always the case but I just noticed now.

Anyway, here is the fix: to force the wheel to honor the MANIFEST.in, you need to specify both `include_package_data` and `packages`.

If your Python module is inside a folder "mymodule", here is how the setup looks like:

```
setup( ...
    include_package_data=True,  # use MANIFEST.in to include config file
    packages=['mymodule'],  # to force the wheel to use the MANIFEST.in
)
```

If all your python scripts are at the root (and not inside a subfolder), use:

```
setup( ...
    include_package_data=True,  # use MANIFEST.in to include config file
    packages=['.'],  # to force the wheel to use the MANIFEST.in
)
```

**Comment by genomeorganizer** [comment] 2021-05-03 18:06
After reading this and other threads, I'm going back to cramming all my data into .py files because that's the only thing that consistently works.

And comment whitewashed in... 3... 2...
